curl -X POST http://localhost:3001/chat/start \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNlY2lsaWEubmFpckBlbWFpbC5jb20iLCJzdWIiOiJmZDg3NGEwNC04MmY1LTQ5ZDItYTZkNC1hYTE0Y2Q3ZGJhYmQiLCJwZXJmaWwiOiJQQUNJRU5URSIsInBlcmZpbElkIjoiZjg1NWJhZDEtNThjMC00M2FmLWIzODgtYzQ5ZTEwMDRhZjM3IiwiaWF0IjoxNzU5MDIwMzAzLCJleHAiOjE3NTkxMDY3MDN9.bfQDrTp6YNH68tAJ8sknbEAyZzBxcsdU5kg5LthRmYQ" \
-H "Content-Type: application/json" \
-d '{
    "pergunta": "Tenho uma cobrança indevida, o que devo fazer?"
}'

###

curl -X POST http://localhost:3001/chat/agendamento \
-H "Content-Type: application/json" \
-d '{
    "pergunta": "Sim"

}'

###
031.627.020-21