curl -X POST http://localhost:3000/consultas \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW8ucGFjaWVudGVAZW1haWwuY29tIiwic3ViIjoiNmY0N2NiZTQtMWI4OS00MGEyLWFlMWItOTc3OThmMDE3NGZkIiwicGVyZmlsIjoiUEFDSUVOVEUiLCJpYXQiOjE3NTg5OTMzNDEsImV4cCI6MTc1OTA3OTc0MX0.EAYDh_DRFY3o633ghOhB2HhHz-VApLA0Yp1KazJyRaI" \
-d '{
  "dataHoraInicio": "2025-10-05T14:30:00.000Z",
  "pacienteId": "ec5ce992-f870-48b9-9831-35d79ca9afcc",
  "medicoId": "30343d6d-f65f-44a7-a1b3-6363e79323aa"
}'

###

curl -X GET http://localhost:3000/consultas \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW8ucGFjaWVudGVAZW1haWwuY29tIiwic3ViIjoiNmY0N2NiZTQtMWI4OS00MGEyLWFlMWItOTc3OThmMDE3NGZkIiwicGVyZmlsIjoiUEFDSUVOVEUiLCJpYXQiOjE3NTg5OTMzNDEsImV4cCI6MTc1OTA3OTc0MX0.EAYDh_DRFY3o633ghOhB2HhHz-VApLA0Yp1KazJyRaI" \

###

curl -X GET http://localhost:3000/consultas/8cb823f3-cfc8-4bbd-9e34-6f456f997a4c \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW8ucGFjaWVudGVAZW1haWwuY29tIiwic3ViIjoiNmY0N2NiZTQtMWI4OS00MGEyLWFlMWItOTc3OThmMDE3NGZkIiwicGVyZmlsIjoiUEFDSUVOVEUiLCJpYXQiOjE3NTg5OTMzNDEsImV4cCI6MTc1OTA3OTc0MX0.EAYDh_DRFY3o633ghOhB2HhHz-VApLA0Yp1KazJyRaI" \